name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # Use caching to speed up npm install
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Optimize dependency installation
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      # Separate build and test steps
      - name: Build Project
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: |
            mpstme-acm/acm-website-24:${{ github.sha }}
            mpstme-acm/acm-website-24:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ENVIRONMENT=production
          labels: |
            maintainer=mpstme-acm
            version=${{ github.sha }}
            description=PFE 24' Website

      - name: Deploy Container
        run: |
          CONTAINER_NAME="acm-web-container"
          
          # Graceful container management
          docker stop "$CONTAINER_NAME" || true
          docker rm "$CONTAINER_NAME" || true
          
          docker run -d \
            --name "$CONTAINER_NAME" \
            -p 3005:3000 \
            --restart unless-stopped \
            mpstme-acm/acm-website-24:latest